global using ADMControl.Dominio.Entidades;
global using ADMControl.Dominio.Repositorios;
global using ADMControl.Dominio.Repositorios.RepCategoria;
global using ADMControl.Dominio.Repositorios.RepColaborador;
global using ADMControl.Dominio.Repositorios.RepProduto;
global using ADMControl.Dominio.Repositorios.RepUnidade;
global using ADMControl.Web.Models;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
