// <auto-generated />
using ADMControl.Dominio.Repositorios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADMControl.Dominio.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20230615130801_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ADMControl.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("CAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CAT_NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CAT_ID");

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("ADMControl.Dominio.Entidades.Unidade", b =>
                {
                    b.Property<int>("UNI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UNI_NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UNI_SIGLA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UNI_ID");

                    b.ToTable("UNIDADE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
